### ISSUE TITLE
example headers

### ISSUE THREAD

**Issue by HassenPy** [AnamikaD/AnamikaD.github.io#1]
Check the 2 on the left:  

![anamikad github io-](https://user-images.githubusercontent.com/7109776/28779002-7fcc3fd0-75f9-11e7-80d3-9d15e6bc1e2e.png)

**Comment by WW-Web-Infra** [comment]
Woho this looks nice! How did you change the colour of the number?

**Comment by HassenPy** [comment]
oh, just used chrome dev tools's color picker and clicked on the charts green color

**Comment by WW-Web-Infra** [comment]
@HassenPy Thanks Hassen!! you are a genius :1st_place_medal:  Updated the header
