### ISSUE TITLE
Changing graphing

### ISSUE THREAD

**Issue by rahulkrishnan98** [AnamikaD/AnamikaD.github.io#2]
Plotting a line graph over static quantities(no change with respect to time) doesn't make sense.
![dashboard1](https://user-images.githubusercontent.com/20839638/28791632-b4e01aba-764a-11e7-8e61-6012f3659cfd.png)
It would be better to create alter graphs which is not based on such time growth.

**Comment by WW-Web-Infra** [comment]
@rahulkrishnan98 Thank you for the feedback! I have changed it to spline graph :)
